M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date  8.04.2025 (вт)  9:34:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-08T09:34:59+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
%
G90
G05
T1
X6.26Y62.97
X12.04Y62.97
T0
M30
